### ISSUE TITLE
Another restart

### ISSUE THREAD

**Issue by MARIOpremiun** [ericz99/instagram-monitor#9]
I don't know if its because of my proxies or a bug cause before that it worked

[17:56:26.001] [godalertsaio] [+] Started task!
[17:56:26.004] [fleekframework] [+] Started task!
[17:56:26.006] [offspringhq] [+] Started task!
Proxy timeout!
[17:56:26.102] [fleekframework] [x] Restarting task...
Proxy timeout!
[17:56:26.134] [offspringhq] [x] Restarting task...
Proxy timeout!
[17:56:26.282] [godalertsaio] [x] Restarting task...
Proxy timeout!
[17:56:26.284] [cybersole] [x] Restarting task...
[17:56:31.113] [fleekframework] [+] Started task!
[17:56:31.150] [offspringhq] [+] Started task!
[17:56:31.285] [godalertsaio] [+] Started task!
[17:56:31.287] [cybersole] [+] Started task!
Proxy timeout!
[17:56:31.330] [fleekframework] [x] Restarting task...
Proxy timeout!
[17:56:31.457] [godalertsaio] [x] Restarting task...
Proxy timeout!
[17:56:31.484] [cybersole] [x] Restarting task...
Proxy timeout!
[17:56:31.621] [offspringhq] [x] Restarting task...
[17:56:36.332] [fleekframework] [+] Started task!
[17:56:36.460] [godalertsaio] [+] Started task!
Proxy timeout!
[17:56:36.493] [fleekframework] [x] Restarting task...
[17:56:36.496] [cybersole] [+] Started task!
[17:56:36.622] [offspringhq] [+] Started task!
Proxy timeout!
[17:56:36.653] [cybersole] [x] Restarting task...
Proxy timeout!
[17:56:36.725] [godalertsaio] [x] Restarting task...
Proxy timeout!
[17:56:36.778] [offspringhq] [x] Restarting task...
[17:56:41.504] [fleekframework] [+] Started task!
Proxy timeout!
[17:56:41.646] [fleekframework] [x] Restarting task...
[17:56:41.655] [cybersole] [+] Started task!
[17:56:41.726] [godalertsaio] [+] Started task!
[17:56:41.780] [offspringhq] [+] Started task!
Proxy timeout!
[17:56:41.914] [godalertsaio] [x] Restarting task...
Proxy timeout!
[17:56:41.919] [cybersole] [x] Restarting task...
Proxy timeout!
[17:56:41.978] [offspringhq] [x] Restarting task...
[17:56:46.660] [fleekframework] [+] Started task!
Proxy timeout!
[17:56:46.858] [fleekframework] [x] Restarting task...
[17:56:46.916] [godalertsaio] [+] Started task!
[17:56:46.921] [cybersole] [+] Started task!
[17:56:46.979] [offspringhq] [+] Started task!
Proxy timeout!
[17:56:47.030] [cybersole] [x] Restarting task...
Proxy timeout!
[17:56:47.057] [godalertsaio] [x] Restarting task...
Proxy timeout!
[17:56:47.109] [offspringhq] [x] Restarting task...
[17:56:51.860] [fleekframework] [+] Started task!
Proxy timeout!
[17:56:51.921] [fleekframework] [x] Restarting task...
[17:56:52.031] [cybersole] [+] Started task!
[17:56:52.059] [godalertsaio] [+] Started task!
[17:56:52.110] [offspringhq] [+] Started task!
Proxy timeout!
[17:56:52.234] [cybersole] [x] Restarting task...
Proxy timeout!
[17:56:52.257] [godalertsaio] [x] Restarting task...
Proxy timeout!
[17:56:52.334] [offspringhq] [x] Restarting task...

**Comment by MARIOpremiun** [comment]
Now i'm getting this 
(C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 50)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 51)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 52)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 53)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 54)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 55)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 56)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 57)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 58)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 59)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 60)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 61)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 62)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 63)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 64)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 65)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 66)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 67)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 68)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 69)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 70)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 71)
(node:2752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Task.length (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task/index.js:92:16)
    at tryCatch (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:28:103)
    at _next (C:\Users\eden_ichak22\Desktop\instagram-monitor-master\libs\task\index.js:30:194)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 72)
